package cvc.dashingdog.intenttester

import android.content.Intent

// Grouped for display in the UI. Order is preserved (LinkedHashMap).
// Values are the actual Android constant integers — no magic numbers.

val INTENT_FLAGS: Map<String, Int> = linkedMapOf(

    // Activity launch behaviour
    "FLAG_ACTIVITY_NEW_TASK"              to Intent.FLAG_ACTIVITY_NEW_TASK,
    "FLAG_ACTIVITY_CLEAR_TOP"             to Intent.FLAG_ACTIVITY_CLEAR_TOP,
    "FLAG_ACTIVITY_SINGLE_TOP"            to Intent.FLAG_ACTIVITY_SINGLE_TOP,
    "FLAG_ACTIVITY_CLEAR_TASK"            to Intent.FLAG_ACTIVITY_CLEAR_TASK,
    "FLAG_ACTIVITY_NO_HISTORY"            to Intent.FLAG_ACTIVITY_NO_HISTORY,
    "FLAG_ACTIVITY_REORDER_TO_FRONT"      to Intent.FLAG_ACTIVITY_REORDER_TO_FRONT,
    "FLAG_ACTIVITY_NO_ANIMATION"          to Intent.FLAG_ACTIVITY_NO_ANIMATION,
    "FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS"  to Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS,
    "FLAG_ACTIVITY_MULTIPLE_TASK"         to Intent.FLAG_ACTIVITY_MULTIPLE_TASK,
    "FLAG_ACTIVITY_FORWARD_RESULT"        to Intent.FLAG_ACTIVITY_FORWARD_RESULT,

    // URI permissions
    "FLAG_GRANT_READ_URI_PERMISSION"          to Intent.FLAG_GRANT_READ_URI_PERMISSION,
    "FLAG_GRANT_WRITE_URI_PERMISSION"         to Intent.FLAG_GRANT_WRITE_URI_PERMISSION,
    "FLAG_GRANT_PERSISTABLE_URI_PERMISSION"   to Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION,
    "FLAG_GRANT_PREFIX_URI_PERMISSION"        to Intent.FLAG_GRANT_PREFIX_URI_PERMISSION,

    // Broadcast behaviour
    "FLAG_RECEIVER_REGISTERED_ONLY"   to Intent.FLAG_RECEIVER_REGISTERED_ONLY,
    "FLAG_RECEIVER_REPLACE_PENDING"   to Intent.FLAG_RECEIVER_REPLACE_PENDING,
    "FLAG_RECEIVER_NO_ABORT"          to Intent.FLAG_RECEIVER_NO_ABORT,
    "FLAG_RECEIVER_FOREGROUND"        to Intent.FLAG_RECEIVER_FOREGROUND,

    // Package targeting
    "FLAG_INCLUDE_STOPPED_PACKAGES"   to Intent.FLAG_INCLUDE_STOPPED_PACKAGES,
    "FLAG_EXCLUDE_STOPPED_PACKAGES"   to Intent.FLAG_EXCLUDE_STOPPED_PACKAGES
)